[package]
name = "sf_motd"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = "0.5.0-rc.2"
reqwest = {version = "0.11.10", features=['blocking', 'json']}
chrono = "0.4.19"
scraper = "0.12.0"

[dev-dependencies]
httpmock = "0.6.6"